[project]
name = "ComfyUI_RIFE_TensorRT_Auto"
description = "Ultra fast frame interpolation using RIFE with TensorRT with Automatic downloading"
version = "1.2.0"
license = { file = "LICENSE" }

[project.urls]
Repository = "https://github.com/huchukato/ComfyUI-RIFE-TensorRT-Auto"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = "huchukato"
DisplayName = "ComfyUI_RIFE_TensorRT_Auto"
Icon = ""
